{{- if .Values.oidc }}
{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-oidc
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
{{- $root := . }}
    oidc.json: '{{ toJson .Values.oidc }}'
{{- end -}}
{{- end -}}